"""Adicionando a coluna 'vendida' à tabela Bolsa

Revision ID: 8dba32f117b5
Revises: 
Create Date: 2025-04-21 18:38:27.581775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dba32f117b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bolsa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendida', sa.Boolean(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('imagem_url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('whatsapp',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bolsa', schema=None) as batch_op:
        batch_op.alter_column('whatsapp',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('imagem_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('vendida')

    # ### end Alembic commands ###
